language: python3

env:
  global:
    - LOCAL_REPO: transformers-inference
    - REMOTE_REPO: semitechnologies/transformers-inference
  jobs:
    - MODEL_NAME=bert-base-uncased
    - MODEL_NAME=distilbert-base-uncased

script: 
  - cicd/build.sh || travis_terminate 1
  - cicd/test.sh || travis_terminate 1
  - |-
    # Push docker image
    GIT_BRANCH=$TRAVIS_BRANCH \
    GIT_TAG=$TRAVIS_TAG \
    GIT_PULL_REQUEST=$TRAVIS_PULL_REQUEST \
    cicd/docker_push.sh || travis_terminate 1

